# Project information
site_name: CBF Academy Student Handbook
site_description: >-
  CBF Academy Student Handbook

theme:
  name: material

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cbfacademy
    - icon: fontawesome/solid/globe
      link: https://academy.codingblackfemales.com

# Page tree
nav:
  - Home: index.md
  - Resources:
    - Personal Portfolios: resources/personal-portfolios.md
    - Spring Boot: resources/spring-boot.md